spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tomatomall?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: cz050128
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    bcrypt:
      enabled: true
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 开启消息确认
    # publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
  amqp:
    deserialization:
      trusted:
        packages:
          - java.util
          - java.lang
          - com.example.tomatomall.dto
  redis:
    host: 192.168.56.10
    port: 6379
    password:
    database: 0
    timeout: 3000

# 自定义队列配置
mq-config:
  order-delay-queue: order.delay.queue
  order-dead-queue: order.dead.queue
  payment-queue: payment.process.queue

jwt:
  secret: "tomato-mall"
  # JWT 过期时间，单位毫秒
  expiration: 864000000
alipay:
  appId: 2021000147671450
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCyOCyLh9THTiXeRKI5YOdOlZDSNWXLiXvLFCJ1g6ChTJTsebqmcravKnt69nl9PtGz5/vKeH9LwPiXdVontcyJG65C9UIFwtGThyG6sWt5qmKq2Na3rwSq23R+xuvvUn2DqkdtBcrHyj6M94ypzvNPYkjjAfBlKGosMWaChxIT8apyz/dSsP4uulfxNfsq4+LO3Y+Gc69aK//ndNYkf1+WMNmXoPo5Ve4K0csj+LIibJ5p5bUz72m1uorhYUlSc4x8pmBiS7CSTNCgaBQsNMdDun8xVkFLqZWv9iTuASKKKrz9cv0F0eL4zSUj+QpVWOCTbwkztWqGSNve1SaU/IBFAgMBAAECggEANS4V/LzXfXGQUzbfwYds/kIbKN7ONWIdEog7kB1q/TbA6Z+ZVrm8UaC3oAWUUw8/vBNpSw2RzqUSiP93m4ngMrmT0l8lCFsN9pvIMNFoZLG3J4v05nLPTbyWko4BMTTIR1W0Yo/r5pou+BmWW8VpTTLi1PprJYRdyjojgKeVeWWONm9uLeon6xYavvJknX+pIg3mSVTvIYXGUlBDb8DDbj2J95+GfTTU+2ziaMbGK8mb2PwR76sPhGDShDdBah0dFMypwa8u2SK1iXnAu03WEc1WowLoc2VaPgzlIA0syczFp9zKOSV79bARifX/fXrvy7YMszVjAiokjEhizuWLMQKBgQD9/5agKa8e9hfQV9058kj6pePJtQY1cH+cWglUBr+gZHTHzveS3RfT6Fs/MmsAKvqIKiwAo7rWDuUsberagOLcRmSARbItA94z5ppEdaLhomojtZr+o057GiaUW8gMdPmA9+Aakyr3Zth1u7Orl7ftN6A9Ap4dzh6+kT1tNeTnNwKBgQCzn7XnFkHVujSYz/+I7tKjcCYeh7YmNJeaX+99t7El/qsnV4oQODniauiEA91nlBCKWtmpGW8uVnPicXMc2nxvQelMDWb6JzSPRCei7e+OMIhuiebH1mlFysKxwa+E5SfQ/BBsIsAyYABsq8WxAkvltbChqDAx99J6AVc5uKCaYwKBgQCCquEfZjJcGDgqC3mY3ObkY0ErPICEL2rG0Z7o5kvgxK07OWMt36Xpcyi1+0cGoBWgxSk77v8oLiOB1s4yOIn8zg3X24MNG2dNhf2o6Gex8i7uTff9tZ+jPtHIEut4VRkiWuKkaT96ZSNIdha5WOTbGXnKyTT0mlxAp1FVhJtMwwKBgCBM4wAIH5SYZGbqWFA+agBb5W7uBpI+ONjY0Y8w3hkv/4UWl8ws4DPX97Hto/3BQWwvxB5FZZnWkAYzUnjozSGQn6w+aLspG6l7nwkMclyGW7JM+AQNiWa0fGhMpQxnzM4m1aksYpVscAcaqHUZLZ7EGlwni2sg3md0IERP8AlzAoGBAL/fxTAGeuVpTMxlU0HPSix9hlly6+2dBj34QEHGEy/o7bPXRN9iyNGFvi5htzGwrqjZXhDcMMJxIlzFTth3N+gsfzsoYu7U0J5SnK5XcRBEKrUfk8SI1lE43BH4ajSn3PrPIzRWskUrTA5SfmhtH+uwxysQGfqsXYoHV7lkKRwi
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl33UntFqkA6FSz8TMzYfggCvJyKqnzD10d/lCY49+tg4Vhqnvq8xHYAVym6Lcy+j5HxzX0p2G8QeuCheIN2D/Uiw1Q1b8Dv9rz86by7+u+d7ofqJX5LV1qEHc1aVAM+/psNvGe4+nSQ1Xj/rgieWqV2IQa0QIE43YyqtrJYOoXi14/pLSC6UAsP0KK7XvAmC71nyNSxzcSW8z6inVluv/7v/cITpmtlQHGNj3+K2+cnQ5BKU+mg64Ulchij2ZH/ZHIazGt8UKPk9TAMU2ZClJ883Fci9Df+ebYISd+f2Q9sUXK1vyWf6wBnxm3xwRjVyKpc+guVF1rSab5pivM/7UQIDAQAB
  notifyUrl: http://qmz26e.natappfree.cc/api/orders/notify
  serverUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  returnUrl: http://www.baidu.com
